version: "3"
  
services:
  service1:
    image: kimovi/service1:latest
    build: ./service1
    deploy:
      replicas: 3
    ports:
    - "5000:5000"

  service2:
    image: kimovi/service2:latest
    build: ./service2
    deploy:
      replicas: 3
    ports:
    - "5001:5001"

  service3:
    image: kimovi/service3:latest
    build: ./service3
    deploy:
      replicas: 3
    ports:
    - "5002:5002"

  service4:
    image: kimovi/service4:latest
    build: ./service4
    deploy:
      replicas: 3
    ports:
    - "5003:5003"