version: "3"

services:
  service1:
    container_name: service1
    image: service1:latest
    build: ./service1
    ports:
    - "5000:5000"
      
  service2:
    container_name: service2
    image: service2:latest
    build: ./service2
    ports:
    - "5001:5001"

  service3:
    container_name: service3
    image: service3:latest
    build: ./service3
    ports:
    - "5002:5002"

  service4:
    container_name: service4
    image: service4:latest
    build: ./service4
    ports:
    - "5003:5003"